FROM python:3.13-slim

# Установка зависимостей для работы Python
RUN apt-get update && apt-get install -y build-essential

WORKDIR /app

# Копируем requirements и устанавливаем зависимости
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Копируем исходники бота
COPY . .

# Указание переменной окружения для Python
ENV PYTHONUNBUFFERED=1

# Запуск
CMD ["python", "bot.py"]
